### ISSUE TITLE
Usa Sass com a sintax scss, fica bem melhor ;)

### ISSUE THREAD

**Issue by orivelton10** [thi-days/thiagodias.me#1]
https://github.com/thi-days/thiagodias.me/blob/c96b4a4f237d7459cee070a81ee4521bdd495e18/.angular-cli.json#L57

**Comment by thi-days** [comment]
Boa dica! Ainda gerei o projeto, mas não tive tempo de configurá-lo. Rsrsrs. Já vou colocar SASS nele.

**Comment by thi-days** [comment]
@orivelton10, agora está alterado as configurações do Angular pra pre-processar o SASS e não mais CSS básico. As alterações foram feitas no PR #5. Valeu pela dica!
